### ISSUE TITLE
TypeError: Cannot read property 'internal' of undefined

### ISSUE THREAD

**Issue by MaxGabriel** [bnfinet/docker-dns#10]
Hi, we're using docker-dns at Heyzap. After switching storage backends from devicemapper to aufs, we started rebuilding all our docker images. During this time, we saw this error in the docker-dns logfile:

```
[DD] error { [Error: HTTP code is 404 which indicates error: no such container - No such container: 7d5525f545e5da7589a3614697518d558c2641a27514fc93e78f9505a695cb05
]
  reason: 'no such container',
  statusCode: 404,
  json: 'No such container: 7d5525f545e5da7589a3614697518d558c2641a27514fc93e78f9505a695cb05\n' }
[DD] warn 2fcd8d624604 could not find service name for  8125/udp on 2fcd8d624604
[DD] warn b541bbb4e787 could not find service name for  5671/tcp on b541bbb4e787
[DD] warn 7c077142e95c could not find service name for  5671/tcp on 7c077142e95c
[DD] warn 9f90d991847c could not find service name for  8125/udp on 9f90d991847c

/app/lib/container-inspect.js:102
                self._buildAnCNAMERecords(self.ips.internal, self.docker.localfqdn, functi
                                                  ^
TypeError: Cannot read property 'internal' of undefined
    at /app/lib/container-inspect.js:102:39
    at /app/node_modules/async/lib/async.js:570:21
    at /app/node_modules/async/lib/async.js:249:17
    at /app/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/app/node_modules/async/lib/async.js:46:24)
    at async.each (/app/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/app/node_modules/async/lib/async.js:248:13)
    at Object.map (/app/node_modules/async/lib/async.js:219:23)
    at _parallel (/app/node_modules/async/lib/async.js:568:20)
Calling docker stop docker-dns
Calling docker rm docker-dns
Calling docker rm docker-dns
Calling docker build --rm -t local/docker-dns /etc/docker-dns
```

It looks like this error occurred 23 times in total.

A larger logfile snippet is available [as a gist](https://gist.github.com/MaxGabriel/cfb3fcd2b4f1a54279f0).

Version info:

```
root@monitor ~# docker info
Containers: 18
Images: 102
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 138
Execution Driver: native-0.2
Kernel Version: 3.13.0-40-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 8
Total Memory: 14.69 GiB
Name: monitor.ec2.heyzap.com
ID: WLCE:UUI6:EJLL:L6ER:GMYE:TUGZ:BOHA:5KQJ:B6IL:SA77:DCBA:LMZ4
WARNING: No swap limit support

root@monitor ~# docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

root@monitor ~# nodejs --version
v0.10.25
```

I _believe_ we're using master of docker-dns, because Dockerfile is doing a git clone of master, and we rebuilt the image right before this error occurred.

I personally am pretty unfamiliar with docker and docker-dns, so I can't promise to be helpful fixing this issue, I just thought you should know about it since there's at least a clear stacktrace to work with.

cc @kcrayon @m5

**Comment by bnfinet** [comment]
Thanks for the detailed report.

Can I ask if container 7d5525f545e5da7589a3614697518d558c2641a27514fc93e78f9505a695cb05 does exist?  Does `docker ps -a` show 7d5525f545e5?  If that is a valid running container is there anything different about it's `docker run`, particularly wrt networking (something like `--net=host`)?

**Comment by MaxGabriel** [comment]
`docker ps -a` doesn't list 7d5525f545e5, no (atleast not at this moment).
